package com.ecp.les_constructions_dominic_cyr.ProjectSubdomain.dataaccesslayer;
import com.ecp.les_constructions_dominic_cyr.backend.ProjectSubdomain.DataAccessLayer.Lot.Lot;
import com.ecp.les_constructions_dominic_cyr.backend.ProjectSubdomain.DataAccessLayer.Lot.LotIdentifier;
import com.ecp.les_constructions_dominic_cyr.backend.ProjectSubdomain.DataAccessLayer.Lot.LotStatus;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LotTest {

    private LotIdentifier lotIdentifier;
    private static final String LOCATION = "Lot 42, Sector B";
    private static final Float PRICE = 150000.00f;
    private static final String DIMENSIONS = "100ft x 150ft";
    private static final LotStatus STATUS = LotStatus.AVAILABLE;
    private static final String IMAGE_ID = "img-lot-123";

    @BeforeEach
    void setUp() {

        lotIdentifier = new LotIdentifier("Lot-ID-A1");
    }

    @Test
    @DisplayName("Primary Constructor should correctly initialize all fields")
    void constructor_InitializesFieldsCorrectly() {

        Lot lot = new Lot(lotIdentifier, LOCATION, PRICE, DIMENSIONS, STATUS);


        assertNotNull(lot.getLotIdentifier(), "LotIdentifier should not be null");
        assertEquals(lotIdentifier, lot.getLotIdentifier(), "LotIdentifier should match the one provided");
        assertEquals(LOCATION, lot.getLocation(), "Location should match the one provided");
        assertEquals(PRICE, lot.getPrice(), "Price should match the one provided");
        assertEquals(DIMENSIONS, lot.getDimensions(), "Dimensions should match the one provided");
        assertEquals(STATUS, lot.getLotStatus(), "LotStatus should match the one provided");
        assertNull(lot.getImageIdentifier(), "ImageIdentifier should be null by default");
        assertNull(lot.getId(), "ID should be null before persistence");
    }

    @Test
    @DisplayName("Setters generated by Lombok @Data should work correctly")
    void setters_WorkCorrectly() {

        Lot lot = new Lot(lotIdentifier, LOCATION, PRICE, DIMENSIONS, STATUS);
        String newLocation = "Lot 99, Sector C";
        String newImageId = "new-img-456";


        lot.setLocation(newLocation);
        lot.setImageIdentifier(newImageId);

        assertEquals(newLocation, lot.getLocation());
        assertEquals(newImageId, lot.getImageIdentifier());
    }
    @Test
    @DisplayName("Constructor throws NullPointerException when LotIdentifier is null")
    void constructor_NullLotIdentifier_ThrowsNPE() {
        assertThrows(NullPointerException.class, () -> {
            new Lot(null, LOCATION, PRICE, DIMENSIONS, STATUS);
        });
    }

    @Test
    @DisplayName("Constructor throws NullPointerException when location is null")
    void constructor_NullLocation_ThrowsNPE() {
        assertThrows(NullPointerException.class, () -> {
            new Lot(lotIdentifier, null, PRICE, DIMENSIONS, STATUS);
        });
    }

    @Test
    @DisplayName("Constructor throws NullPointerException when price is null")
    void constructor_NullPrice_ThrowsNPE() {
        assertThrows(NullPointerException.class, () -> {
            new Lot(lotIdentifier, LOCATION, null, DIMENSIONS, STATUS);
        });
    }

    @Test
    @DisplayName("Constructor throws NullPointerException when dimensions is null")
    void constructor_NullDimensions_ThrowsNPE() {
        assertThrows(NullPointerException.class, () -> {
            new Lot(lotIdentifier, LOCATION, PRICE, null, STATUS);
        });
    }

    @Test
    @DisplayName("Constructor throws NullPointerException when LotStatus is null")
    void constructor_NullLotStatus_ThrowsNPE() {
        assertThrows(NullPointerException.class, () -> {
            new Lot(lotIdentifier, LOCATION, PRICE, DIMENSIONS, null);
        });
    }

}