package com.ecp.les_constructions_dominic_cyr.ProjectSubdomain.dataaccesslayer;

import com.ecp.les_constructions_dominic_cyr.backend.ProjectSubdomain.DataAccessLayer.Renovation.Renovation;
import com.ecp.les_constructions_dominic_cyr.backend.ProjectSubdomain.DataAccessLayer.Renovation.RenovationIdentifier;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class RenovationTest {

    private RenovationIdentifier renovationIdentifier;
    private static final String BEFORE_IMAGE_ID = "before-img-123";
    private static final String AFTER_IMAGE_ID = "after-img-456";
    private static final String DESCRIPTION = "Complete kitchen renovation with modern appliances";

    @BeforeEach
    void setUp() {
        renovationIdentifier = new RenovationIdentifier("Renovation-ID-A1");
    }

    @Test
    @DisplayName("Primary Constructor should correctly initialize all fields")
    void constructor_InitializesFieldsCorrectly() {

        Renovation renovation = new Renovation(renovationIdentifier, BEFORE_IMAGE_ID, AFTER_IMAGE_ID, DESCRIPTION);


        assertNotNull(renovation.getRenovationIdentifier(), "RenovationIdentifier should not be null");
        assertEquals(renovationIdentifier, renovation.getRenovationIdentifier(), "RenovationIdentifier should match the one provided");
        assertEquals(BEFORE_IMAGE_ID, renovation.getBeforeImageIdentifier(), "Before image identifier should match the one provided");
        assertEquals(AFTER_IMAGE_ID, renovation.getAfterImageIdentifier(), "After image identifier should match the one provided");
        assertEquals(DESCRIPTION, renovation.getDescription(), "Description should match the one provided");
        assertNull(renovation.getId(), "ID should be null before persistence");
    }

    @Test
    @DisplayName("Setters generated by Lombok @Data should work correctly")
    void setters_WorkCorrectly() {

        Renovation renovation = new Renovation(renovationIdentifier, BEFORE_IMAGE_ID, AFTER_IMAGE_ID, DESCRIPTION);
        String newDescription = "Updated bathroom renovation";
        String newAfterImage = "new-after-img-789";


        renovation.setDescription(newDescription);
        renovation.setAfterImageIdentifier(newAfterImage);

        assertEquals(newDescription, renovation.getDescription());
        assertEquals(newAfterImage, renovation.getAfterImageIdentifier());
    }

    @Test
    @DisplayName("Constructor throws NullPointerException when RenovationIdentifier is null")
    void constructor_NullRenovationIdentifier_ThrowsNPE() {
        assertThrows(NullPointerException.class, () -> {
            new Renovation(null, BEFORE_IMAGE_ID, AFTER_IMAGE_ID, DESCRIPTION);
        });
    }

    @Test
    @DisplayName("Constructor throws NullPointerException when before image identifier is null")
    void constructor_NullBeforeImageIdentifier_ThrowsNPE() {
        assertThrows(NullPointerException.class, () -> {
            new Renovation(renovationIdentifier, null, AFTER_IMAGE_ID, DESCRIPTION);
        });
    }

    @Test
    @DisplayName("Constructor throws NullPointerException when after image identifier is null")
    void constructor_NullAfterImageIdentifier_ThrowsNPE() {
        assertThrows(NullPointerException.class, () -> {
            new Renovation(renovationIdentifier, BEFORE_IMAGE_ID, null, DESCRIPTION);
        });
    }

    @Test
    @DisplayName("Constructor throws NullPointerException when description is null")
    void constructor_NullDescription_ThrowsNPE() {
        assertThrows(NullPointerException.class, () -> {
            new Renovation(renovationIdentifier, BEFORE_IMAGE_ID, AFTER_IMAGE_ID, null);
        });
    }
}
