package com.ecp.les_constructions_dominic_cyr.backend.ProjectSubdomain.DataAccessLayer.Quote;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "quotes")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Quote {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "quote_id")
    private Long quoteId;

    /**
     * Sequential quote number in format: QT-XXXXXXX (7 digits, zero-padded)
     * Example: QT-0000001, QT-0000002, etc.
     * Generated by the system, never provided by frontend.
     * UNIQUE and NOT NULL - enforced at database level.
     */
    @Column(name = "quote_number", nullable = false, unique = true, length = 15)
    private String quoteNumber;

    @Column(name = "project_identifier", nullable = false)
    private String projectIdentifier;

    @Column(name = "lot_identifier", nullable = true)
    private String lotIdentifier;

    @Column(name = "category", nullable = true, length = 100)
    private String category;

    @Column(name = "contractor_id", nullable = false)
    private String contractorId;

    @OneToMany(
        mappedBy = "quote",
        cascade = CascadeType.ALL,
        orphanRemoval = true,
        fetch = FetchType.EAGER
    )
    private List<QuoteLineItem> lineItems = new ArrayList<>();

    /**
     * Total amount auto-calculated from all line items.
     * Precision: DECIMAL(15,2) for currency (supports up to 13 digits before decimal).
     */
    @Column(name = "total_amount", nullable = false, columnDefinition = "DECIMAL(15,2) DEFAULT 0.00")
    private BigDecimal totalAmount;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Lifecycle hooks to automatically manage timestamps.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
        if (totalAmount == null) {
            totalAmount = BigDecimal.ZERO;
        }
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    /**
     * Recalculate the total amount from all line items.
     * Called before persistence to ensure data integrity.
     */
    public void recalculateTotal() {
        if (lineItems == null || lineItems.isEmpty()) {
            this.totalAmount = BigDecimal.ZERO;
        } else {
            this.totalAmount = lineItems.stream()
                .map(QuoteLineItem::getLineTotal)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        }
    }
}
