package com.ecp.les_constructions_dominic_cyr.backend.ProjectSubdomain.MapperLayer;

import com.ecp.les_constructions_dominic_cyr.backend.ProjectSubdomain.DataAccessLayer.Quote.Quote;
import com.ecp.les_constructions_dominic_cyr.backend.ProjectSubdomain.DataAccessLayer.Quote.QuoteLineItem;
import com.ecp.les_constructions_dominic_cyr.backend.ProjectSubdomain.PresentationLayer.Quote.QuoteRequestModel;
import com.ecp.les_constructions_dominic_cyr.backend.ProjectSubdomain.PresentationLayer.Quote.QuoteResponseModel;
import org.springframework.security.core.Authentication;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.UUID;
import java.util.stream.Collectors;

@Component
public class QuoteMapper {

    /**
     * Convert QuoteRequestModel to Quote entity.
     * Quote number is NOT set here - it's generated by the service.
     * Line items are created and linked to the quote.
     */
    public Quote requestModelToEntity(
        QuoteRequestModel requestModel,
        String quoteNumber,
        String contractorId
    ) {
        Quote quote = Quote.builder()
            .quoteNumber(quoteNumber)
            .projectIdentifier(requestModel.getProjectIdentifier())
            .lotIdentifier(requestModel.getLotIdentifier() != null && !requestModel.getLotIdentifier().isBlank() 
                ? UUID.fromString(requestModel.getLotIdentifier()) 
                : null)
            .category(requestModel.getCategory())
            .contractorId(contractorId)
            .totalAmount(BigDecimal.ZERO) // Will be recalculated
            .build();

        // Map line items
        if (requestModel.getLineItems() != null) {
            quote.setLineItems(
                requestModel.getLineItems().stream()
                    .map(item -> mapLineItemRequestToEntity(item, quote))
                    .collect(Collectors.toList())
            );
        }

        // Recalculate total from line items
        quote.recalculateTotal();

        return quote;
    }

    /**
     * Convert Quote entity to QuoteResponseModel.
     */
    public QuoteResponseModel entityToResponseModel(Quote quote) {
        return QuoteResponseModel.builder()
            .quoteNumber(quote.getQuoteNumber())
            .projectIdentifier(quote.getProjectIdentifier())
            .lotIdentifier(quote.getLotIdentifier() != null ? quote.getLotIdentifier().toString() : null)
            .category(quote.getCategory())
            .contractorId(quote.getContractorId())
            .lineItems(
                quote.getLineItems().stream()
                    .map(this::mapLineItemEntityToResponse)
                    .collect(Collectors.toList())
            )
            .totalAmount(quote.getTotalAmount())
            .createdAt(quote.getCreatedAt())
            .updatedAt(quote.getUpdatedAt())
            .build();
    }

    /**
     * Convert QuoteLineItemRequestModel to QuoteLineItem entity.
     */
    private QuoteLineItem mapLineItemRequestToEntity(
        QuoteRequestModel.QuoteLineItemRequestModel requestItem,
        Quote quote
    ) {
        BigDecimal lineTotal = requestItem.getQuantity().multiply(requestItem.getRate());

        return QuoteLineItem.builder()
            .quote(quote)
            .itemDescription(requestItem.getItemDescription())
            .quantity(requestItem.getQuantity())
            .rate(requestItem.getRate())
            .lineTotal(lineTotal)
            .displayOrder(requestItem.getDisplayOrder())
            .build();
    }

    /**
     * Convert QuoteLineItem entity to QuoteLineItemResponseModel.
     */
    private QuoteResponseModel.QuoteLineItemResponseModel mapLineItemEntityToResponse(
        QuoteLineItem lineItem
    ) {
        return QuoteResponseModel.QuoteLineItemResponseModel.builder()
            .lineItemId(lineItem.getLineItemId())
            .itemDescription(lineItem.getItemDescription())
            .quantity(lineItem.getQuantity())
            .rate(lineItem.getRate())
            .lineTotal(lineItem.getLineTotal())
            .displayOrder(lineItem.getDisplayOrder())
            .build();
    }

    /**
     * Extract contractor ID from authentication.
     */
    public static String getContractorIdFromAuth(Authentication authentication) {
        if (authentication == null || !(authentication.getPrincipal() instanceof Jwt)) {
            throw new IllegalArgumentException("Invalid authentication");
        }

        Jwt jwt = (Jwt) authentication.getPrincipal();
        return jwt.getSubject();
    }

    /**
     * Check if user is a contractor (has ROLE_CONTRACTOR authority).
     */
    public static boolean isContractor(Authentication authentication) {
        return authentication.getAuthorities().stream()
            .map(GrantedAuthority::getAuthority)
            .anyMatch(auth -> auth.equals("ROLE_CONTRACTOR"));
    }
}
