package com.ecp.les_constructions_dominic_cyr.backend.ProjectSubdomain.PresentationLayer.Quote;

import com.ecp.les_constructions_dominic_cyr.backend.ProjectSubdomain.BusinessLayer.Quote.QuoteService;
import com.ecp.les_constructions_dominic_cyr.backend.ProjectSubdomain.MapperLayer.QuoteMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.web.bind.annotation.*;
import jakarta.validation.Valid;
import java.util.List;

@Slf4j
@RestController
@RequestMapping("/api/v1/quotes")
@RequiredArgsConstructor
@CrossOrigin(origins = "http://localhost:3000")
public class QuoteController {

    private final QuoteService quoteService;

    /**
     * Create a new quote under a project.
     * 
     * Constraints:
     * - Only contractors can create quotes
     * - Contractor must be assigned to the project
     * - Quote number is auto-generated by the backend (never provided by frontend)
     * - Line items are validated for quantity > 0 and rate >= 0
     * 
     * @param requestModel Quote data with line items
     * @param authentication Current user's authentication
     * @return The created quote with system-generated quote number
     */
    @PostMapping
    @PreAuthorize("hasRole('CONTRACTOR')")
    public ResponseEntity<QuoteResponseModel> createQuote(
        @Valid @RequestBody QuoteRequestModel requestModel,
        Authentication authentication
    ) {
        log.info("Creating quote for project: {}", requestModel.getProjectIdentifier());

        String contractorId = QuoteMapper.getContractorIdFromAuth(authentication);
        QuoteResponseModel createdQuote = quoteService.createQuote(requestModel, contractorId);

        return ResponseEntity.status(HttpStatus.CREATED).body(createdQuote);
    }

    /**
     * Get all quotes for a specific project.
     * 
     * Accessible to:
     * - Owner (all quotes)
     * - Salesperson (all quotes for assigned projects)
     * - Customer (quotes for their projects)
     * - Contractor (their own quotes)
     * 
     * @param projectIdentifier The project identifier
     * @return List of quotes for the project
     */
    @GetMapping("/project/{projectIdentifier}")
    @PreAuthorize("hasAnyRole('OWNER', 'SALESPERSON', 'CUSTOMER', 'CONTRACTOR')")
    public ResponseEntity<List<QuoteResponseModel>> getQuotesByProject(
        @PathVariable String projectIdentifier
    ) {
        log.info("Fetching quotes for project: {}", projectIdentifier);

        List<QuoteResponseModel> quotes = quoteService.getQuotesByProject(projectIdentifier);
        return ResponseEntity.ok(quotes);
    }

    /**
     * Get all quotes for a specific lot.
     * 
     * Accessible to:
     * - Owner (all quotes)
     * - Salesperson (all quotes for assigned lots)
     * - Customer (quotes for their lots)
     * - Contractor (their own quotes for the lot)
     * 
     * @param lotIdentifier The lot identifier (UUID)
     * @return List of quotes for the lot
     */
    @GetMapping("/lot/{lotIdentifier}")
    @PreAuthorize("hasAnyRole('OWNER', 'SALESPERSON', 'CUSTOMER', 'CONTRACTOR')")
    public ResponseEntity<List<QuoteResponseModel>> getQuotesByLot(
        @PathVariable String lotIdentifier
    ) {
        log.info("Fetching quotes for lot: {}", lotIdentifier);

        List<QuoteResponseModel> quotes = quoteService.getQuotesByLot(lotIdentifier);
        return ResponseEntity.ok(quotes);
    }

    /**
     * Get a specific quote by its quote number (QT-XXXXXXX format).
     * 
     * @param quoteNumber The quote number (e.g., QT-0000001)
     * @return The quote details
     */
    @GetMapping("/{quoteNumber}")
    @PreAuthorize("hasAnyRole('OWNER', 'SALESPERSON', 'CUSTOMER', 'CONTRACTOR')")
    public ResponseEntity<QuoteResponseModel> getQuoteByNumber(
        @PathVariable String quoteNumber
    ) {
        log.info("Fetching quote: {}", quoteNumber);

        QuoteResponseModel quote = quoteService.getQuoteByNumber(quoteNumber);
        return ResponseEntity.ok(quote);
    }

    /**
     * Get all quotes created by the current contractor.
     * 
     * @param authentication Current user's authentication
     * @return List of quotes created by this contractor
     */
    @GetMapping("/my-quotes")
    @PreAuthorize("hasRole('CONTRACTOR')")
    public ResponseEntity<List<QuoteResponseModel>> getMyQuotes(
        Authentication authentication
    ) {
        log.info("Fetching quotes for current contractor");

        String contractorId = QuoteMapper.getContractorIdFromAuth(authentication);
        List<QuoteResponseModel> quotes = quoteService.getQuotesByContractor(contractorId);
        return ResponseEntity.ok(quotes);
    }
}
