@startuml
title Salesperson View Project Page SSD

actor Salesperson

loop for every request attempt
 alt valid SalespersonIdentifier && valid projectIdentifier
 Salesperson -> System: inquireOnProjectPage (projectIdentifier, SalespersonIdentifier)
    System --> Salesperson:  projectIdentifier, SalespersonIdentifier, projectName, projectDescription, lastUpdated, city, startDate, projectColor, projectStatus, progressPercentage
    Salesperson -> System: inquireOnSchedule_&_Milestones(projectIdentifier, SalespersonIdentifier, scheduleIdentifier)
    System --> Salesperson: projectIdentifier, SalespersonIdentifier, scheduleIdentifier, updatedOn, completionDate, UpcomingWork
 else invalid SalespersonIdentifier || invalid projectIdentifier
     Salesperson -> System: inquireOnProjectPage(projectIdentifier, SalespersonIdentifier)
     System --> Salesperson: HTTPstatus, errorMessage
 end


@enduml
