package com.ecp.les_constructions_dominic_cyr.backend.ProjectSubdomain.dataaccesslayer;
import com.ecp.les_constructions_dominic_cyr.backend.ProjectSubdomain.DataAccessLayer.Lot.Lot;
import com.ecp.les_constructions_dominic_cyr.backend.ProjectSubdomain.DataAccessLayer.Lot.LotIdentifier;
import com.ecp.les_constructions_dominic_cyr.backend.ProjectSubdomain.DataAccessLayer.Lot.LotStatus;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LotTest {

    private LotIdentifier lotIdentifier;
    private static final String CIVIC_ADDRESS = "Lot 42, Sector B";
    private static final Float PRICE = 150000.00f;
    private static final String DIMENSIONS_SQ_FT = "15000";
    private static final String DIMENSIONS_SQ_M = "1393.5";
    private static final LotStatus STATUS = LotStatus.AVAILABLE;

    @BeforeEach
    void setUp() {

        lotIdentifier = new LotIdentifier("Lot-ID-A1");
    }

    @Test
    @DisplayName("Primary Constructor should correctly initialize all fields")
    void constructor_InitializesFieldsCorrectly() {

        Lot lot = new Lot(lotIdentifier, CIVIC_ADDRESS, PRICE, DIMENSIONS_SQ_FT, DIMENSIONS_SQ_M, STATUS);


        assertNotNull(lot.getLotIdentifier(), "LotIdentifier should not be null");
        assertEquals(lotIdentifier, lot.getLotIdentifier(), "LotIdentifier should match the one provided");
        assertEquals(CIVIC_ADDRESS, lot.getCivicAddress(), "Civic address should match the one provided");
        assertEquals(PRICE, lot.getPrice(), "Price should match the one provided");
        assertEquals(DIMENSIONS_SQ_FT, lot.getDimensionsSquareFeet(), "Dimensions in square feet should match the one provided");
        assertEquals(DIMENSIONS_SQ_M, lot.getDimensionsSquareMeters(), "Dimensions in square meters should match the one provided");
        assertEquals(STATUS, lot.getLotStatus(), "LotStatus should match the one provided");
        assertNull(lot.getId(), "ID should be null before persistence");
    }

    @Test
    @DisplayName("Setters generated by Lombok @Data should work correctly")
    void setters_WorkCorrectly() {

        Lot lot = new Lot(lotIdentifier, CIVIC_ADDRESS, PRICE, DIMENSIONS_SQ_FT, DIMENSIONS_SQ_M, STATUS);
        String newCivicAddress = "Lot 99, Sector C";
        String newDimensionsSqFt = "20000";
        String newDimensionsSqM = "1858.0";


        lot.setCivicAddress(newCivicAddress);
        lot.setDimensionsSquareFeet(newDimensionsSqFt);
        lot.setDimensionsSquareMeters(newDimensionsSqM);

        assertEquals(newCivicAddress, lot.getCivicAddress());
        assertEquals(newDimensionsSqFt, lot.getDimensionsSquareFeet());
        assertEquals(newDimensionsSqM, lot.getDimensionsSquareMeters());
    }
    @Test
    @DisplayName("Constructor throws NullPointerException when LotIdentifier is null")
    void constructor_NullLotIdentifier_ThrowsNPE() {
        assertThrows(NullPointerException.class, () -> {
            new Lot(null, CIVIC_ADDRESS, PRICE, DIMENSIONS_SQ_FT, DIMENSIONS_SQ_M, STATUS);
        });
    }

    @Test
    @DisplayName("Constructor throws NullPointerException when civic address is null")
    void constructor_NullCivicAddress_ThrowsNPE() {
        assertThrows(NullPointerException.class, () -> {
            new Lot(lotIdentifier, null, PRICE, DIMENSIONS_SQ_FT, DIMENSIONS_SQ_M, STATUS);
        });
    }

    @Test
    @DisplayName("Constructor throws NullPointerException when price is null")
    void constructor_NullPrice_ThrowsNPE() {
        assertThrows(NullPointerException.class, () -> {
            new Lot(lotIdentifier, CIVIC_ADDRESS, null, DIMENSIONS_SQ_FT, DIMENSIONS_SQ_M, STATUS);
        });
    }

    @Test
    @DisplayName("Constructor throws NullPointerException when dimensions square feet is null")
    void constructor_NullDimensionsSquareFeet_ThrowsNPE() {
        assertThrows(NullPointerException.class, () -> {
            new Lot(lotIdentifier, CIVIC_ADDRESS, PRICE, null, DIMENSIONS_SQ_M, STATUS);
        });
    }

    @Test
    @DisplayName("Constructor throws NullPointerException when dimensions square meters is null")
    void constructor_NullDimensionsSquareMeters_ThrowsNPE() {
        assertThrows(NullPointerException.class, () -> {
            new Lot(lotIdentifier, CIVIC_ADDRESS, PRICE, DIMENSIONS_SQ_FT, null, STATUS);
        });
    }

    @Test
    @DisplayName("Constructor throws NullPointerException when LotStatus is null")
    void constructor_NullLotStatus_ThrowsNPE() {
        assertThrows(NullPointerException.class, () -> {
            new Lot(lotIdentifier, CIVIC_ADDRESS, PRICE, DIMENSIONS_SQ_FT, DIMENSIONS_SQ_M, null);
        });
    }

}